### PR TITLE
Fix JDI method invocation in expression evaluator

### PR DESCRIPTION
**Pull request by tdudzik**
Fixes error: `Failed to get variables. Reason: com.sun.jdi.InvalidStackFrameException` which occurs after any expression evaluation.

### CODE REVIEW

**Comment by adpi2** [comment]
Nice fix @tdudzik. Do you think it is possible to add a test?

**Comment by tdudzik** [comment]
> Nice fix @tdudzik. Do you think it is possible to add a test?

Yes, I've just added a test.

**Review by adpi2 — APPROVED** [review]
Thanks

**Comment by adpi2** [comment]
Actually there is a small problem with the unit tests here. Because the `MainDebuggeeRunner.evaluationClassLoader` is always 2.12.4 but that does not work with the `Scala213DebugTests` and `Scala3DebugTests`. So we should probably resolve the correct expression evaluator in `MainDebuggeeRunner` using Coursier (as we do already to resolve the correct Scala library).

**Pull request merged**
