### PR TITLE
chore: Add support for Scala 2.13.9

### PR DESCRIPTION
**Pull request by tgodzik**

### CODE REVIEW

**Comment by tgodzik** [comment]
@adpi2 Could you release expression evaluator for Scala 2.13.9? Maybe we could just configure a job that would run the release on a tag that we have in Metals?

**Comment by adpi2** [comment]
Yes I am going to release it and yes we should have a job :)

**Comment by tgodzik** [comment]
> Yes I am going to release it and yes we should have a job :)

Thanks! Locally running tests I am getting a lot of:
```
Exception in thread "Event Hub" io.reactivex.exceptions.OnErrorNotImplementedException: Empty encoded value for java.lang.String
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
        at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:74)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:64)
        at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
        at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:265)
        at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:184)
        at com.microsoft.java.debug.core.EventHub.lambda$start$0(EventHub.java:82)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.Exception: Empty encoded value for java.lang.String
```
Any idea why that is?

**Comment by adpi2** [comment]
> Any idea why that is?

No idea. What's the full stack trace?

**Comment by tgodzik** [comment]
It's something in microsoft debug server, but no idea why it would throw `OnErrorNotImplementedException`
```
Exception in thread "Event Hub" io.reactivex.exceptions.OnErrorNotImplementedException: Empty encoded value for java.lang.String
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
        at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:74)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:64)
        at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
        at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:265)
        at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:184)
        at com.microsoft.java.debug.core.EventHub.lambda$start$0(EventHub.java:82)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.Exception: Empty encoded value for java.lang.String
        at ch.epfl.scala.debugadapter.internal.stepfilter.Scala2StepFilter.ifEmpty$lzycompute$1(Scala2StepFilter.scala:352)
        at ch.epfl.scala.debugadapter.internal.stepfilter.Scala2StepFilter.ifEmpty$1(Scala2StepFilter.scala:351)
        at ch.epfl.scala.debugadapter.internal.stepfilter.Scala2StepFilter.$anonfun$matchTypeSymbol$1(Scala2StepFilter.scala:358)
        at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
        at scala.Option.fold(Option.scala:251)
        at ch.epfl.scala.debugadapter.internal.stepfilter.Scala2StepFilter.matchTypeSymbol(Scala2StepFilter.scala:358)
        at ch.epfl.scala.debugadapter.internal.stepfilter.Scala2StepFilter.matchType(Scala2StepFilter.scala:218)
        at ch.epfl.scala.debugadapter.internal.stepfilter.Scala2StepFilter.matchReturnType$1(Scala2StepFilter.scala:153)
        at ch.epfl.scala.debugadapter.internal.stepfilter.Scala2StepFilter.matchSignature(Scala2StepFilter.scala:160)
        at ch.epfl.scala.debugadapter.internal.stepfilter.Scala2StepFilter.matchSymbol(Scala2StepFilter.scala:105)
        at ch.epfl.scala.debugadapter.internal.stepfilter.Scala2StepFilter.$anonfun$skipScalaMethod$3(Scala2StepFilter.scala:30)
        at ch.epfl.scala.debugadapter.internal.stepfilter.Scala2StepFilter.$anonfun$skipScalaMethod$3$adapted(Scala2StepFilter.scala:30)
        at scala.collection.TraversableLike.$anonfun$filterImpl$1(TraversableLike.scala:304)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:303)
        at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:297)
        at scala.collection.AbstractTraversable.filterImpl(Traversable.scala:108)
        at scala.collection.TraversableLike.filter(TraversableLike.scala:395)
        at scala.collection.TraversableLike.filter$(TraversableLike.scala:395)
        at scala.collection.AbstractTraversable.filter(Traversable.scala:108)
        at ch.epfl.scala.debugadapter.internal.stepfilter.Scala2StepFilter.skipScalaMethod(Scala2StepFilter.scala:30)
        at ch.epfl.scala.debugadapter.internal.stepfilter.ScalaStepFilter.skip(ScalaStepFilter.scala:26)
        at ch.epfl.scala.debugadapter.internal.stepfilter.ScalaStepFilter.skip$(ScalaStepFilter.scala:15)
        at ch.epfl.scala.debugadapter.internal.stepfilter.Scala2StepFilter.skip(Scala2StepFilter.scala:10)
        at ch.epfl.scala.debugadapter.internal.StepFilterProvider.$anonfun$skip$1(StepFilterProvider.scala:20)
        at ch.epfl.scala.debugadapter.internal.StepFilterProvider.$anonfun$skip$1$adapted(StepFilterProvider.scala:20)
        at scala.collection.LinearSeqOptimized.exists(LinearSeqOptimized.scala:95)
        at scala.collection.LinearSeqOptimized.exists$(LinearSeqOptimized.scala:92)
        at scala.collection.immutable.List.exists(List.scala:91)
        at ch.epfl.scala.debugadapter.internal.StepFilterProvider.skip(StepFilterProvider.scala:20)
        at com.microsoft.java.debug.core.adapter.handler.StepRequestHandler.shouldFilterLocation(StepRequestHandler.java:223)
        at com.microsoft.java.debug.core.adapter.handler.StepRequestHandler.handleDebugEvent(StepRequestHandler.java:170)
        at com.microsoft.java.debug.core.adapter.handler.StepRequestHandler.lambda$handle$1(StepRequestHandler.java:85)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:60)
        ... 5 more
```

**Comment by adpi2** [comment]
That's because we throw an exception in the `StepFilterProvider` and the java debug server does not know how to consume this exception.

**Comment by adpi2** [comment]
Looking at `Caused by: java.lang.Exception: Empty encoded value for java.lang.String` it seems that the debugger cannot load the JDK. What is your Java version?

**Review by adpi2 — APPROVED** [review]

**Pull request merged**
